steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/angular-land-438802-e4/devopsassignment2:${COMMIT_SHA}', '.']

  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/angular-land-438802-e4/devopsassignment2:${COMMIT_SHA}']

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
